# Generated by Django 6.0.1 on 2026-02-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_weather_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
